### ISSUE TITLE
Allow using remote execution of uncommitted code locally

### ISSUE THREAD

**Issue by igorbrites** [AzBuilder/terrakube#1015]
### Bug description 🐞

I've read the issue https://github.com/AzBuilder/terrakube/issues/596, though I think my problem is different. When using Terraform Cloud, if you run plans using local (uncommitted) code, this code is somehow uploaded to TFC runners and planned as needed even if the workspace has a VCS connection configured.

Right now I'm evaluating the change to Terrakube (workspaces and modules), and I need to test the connection using Terrakube's OIDC provider created using [this code](https://github.com/AzBuilder/terrakube/tree/main/dynamic-credential-setup/aws), but if I run a plan locally with the backend changes, it still tries to run the code from my main branch.

I can't set up multiple Terraform tokens on GitHub Actions right now, and I haven't move the modules there yet, so I need to test the AWS authentication on the executors, but with my local code. How can we achieve it?

### Steps to reproduce

- Create a workspace linked to a VCS;
- Have the code applied on the main branch;
- Do changes locally;
- Run a plan.

### Expected behavior

Code gets pushed to the executors and the plan occurs as normal.

**Comment by alfespa17** [comment]
I think this was fixed here:

https://github.com/AzBuilder/terrakube/issues/661

**Comment by igorbrites** [comment]
Ok so I got this working as you said, but the credentials are not working. The provider block has an `assume_role` in it, so my question now is, on the assume role policy, should I add the role or the OIDC provider?

**Comment by alfespa17** [comment]
Basically you only need to add this environment variables in your code and it should work

![image](https://github.com/AzBuilder/terrakube/assets/4461895/a5f42776-b73e-44d7-a084-fb3915990552)

There is one example terraform code here

https://github.com/AzBuilder/terrakube/tree/main/dynamic-credential-setup/aws

**Comment by alfespa17** [comment]
Quick question did you add your private and public key to Terrakube?

**Comment by igorbrites** [comment]
> Quick question did you add your private and public key to Terrakube?

Yes, I did. I created them using Terraform, then created a secret on Kubernetes with them, and mounted them inside the API.

Here is the TF Code:

```hcl
resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

data "tls_public_key" "this" {
  private_key_pem = tls_private_key.this.private_key_pem
}

resource "kubernetes_secret_v1" "certificates" {
  metadata {
    name      = "aws-credentials-certificate"
    namespace = "terrakube"
  }

  data = {
    "private_key" = tls_private_key.this.private_key_pem
    "public_key"  = data.tls_public_key.this.public_key_pem
  }
}
```

And here are the Helm values:

```yaml
api:
  volumeMounts:
  - mountPath: /tmp/aws-credentials
    name: aws-credentials-certificate
    readOnly: true
  volumes:
  - name: aws-credentials-certificate
    secret:
      defaultMode: 420
      secretName: aws-credentials-certificate
  env:
  - name: DynamicCredentialPublicKeyPath
    value: /tmp/aws-credentials/public_key
  - name: DynamicCredentialPrivateKeyPath
    value: /tmp/aws-credentials/private_key
```
