### ISSUE TITLE
App doesn't use cacerts included in the bundled JRE library

### ISSUE THREAD

**Issue by stanleyz** [AzBuilder/terrakube#1091]
### Bug description 🐞

API and Executor, and likely registry as well don't use the cacerts keystore provided by the bundled JRE located in `/layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts`, which I'd assume should be the default behaviour if no customised keystone is specified.

### Steps to reproduce

Create a Redis cache or PostgreSQL with SSL enabled on Azure and configure Terrakube API or Executor to run with them (on SSL)

### Expected behavior

The app starts without issues since the Azure root certs is already loaded into `layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts`

**Comment by alfespa17** [comment]
That is automatically added inside the container using the ca-certificate buildpack from [here](https://github.com/paketo-buildpacks/ca-certificates)

Example when building the image:
![image](https://github.com/user-attachments/assets/2ca41c0b-ad6a-4e37-be18-f518df840ae8)


The CA certificates are added internally as you can see in the following images:

![image](https://github.com/user-attachments/assets/7c0164ce-08ef-472f-ac0b-803e533cfe10)

![image](https://github.com/user-attachments/assets/7cad7c20-739d-45cf-8cb1-7fb1b5d70a5e)

You can add additional CA certificates as we explained [here](https://docs.terrakube.io/getting-started/deployment/custom-ca-certs)

I am not a go expert but I think the values are taken from [here](https://github.com/paketo-buildpacks/ca-certificates/blob/4a9072d601facde66cfb329d1cfe86e6212de924/cacerts/certs.go#L44)

**Comment by stanleyz** [comment]
yes, there is no problem adding a customised CA certificate or the ca-certificates provided by `paketo-buildpacks`, the problems I saw are that:

1.  Liquibase doesn't use the ca-certificates provided by `paketo-buildpacker` and installed to `jre/lib/ca-certificates`
2. Redis connection still requires `TerrakubeSSLTruststorePath` and password to be set, however, it doesn't necessarily need to because the connection should default to use the trust store provided by the JRE, and additionally with the above method provided, users can add customised CA certificates to the JRE truststore.

**Comment by alfespa17** [comment]
I did some progress with this one in this PR https://github.com/AzBuilder/terrakube/pull/1391 when using REDIS and SSL

**Comment by alfespa17** [comment]
I did more progress with this one. I was able to connect successfully to an Azure Redis with SSL enabled using the following with a custom image that I built that included the fix:

```yaml
api:
  version: "2.23.2+small fix from AzBuilder/terrakube#1391"
  image: "api-server"
  defaultRedis: false
  defaultDatabase: true
  loadSampleData: true
  env:
  - name: TerrakubeRedisSSL
    value: "true"
  - name: TerrakubeRedisTruststorePath
    value: /layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts 
  - name: TerrakubeRedisTruststorePassword
    value: changeit
  properties:
    redisHostname: "MY-REDIS-IN-AZURE.redis.cache.windows.net"
    redisPassword: "MY-REDIS-ACCESS-KEY"
    redisPort: "6380"

executor:
  version: "2.23.2"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  - name: TerrakubeRedisSSL
    value: "true"
  - name: TerrakubeRedisTruststorePath
    value: /layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts 
  - name: TerrakubeRedisTruststorePassword
    value: changeit
```

> "changeit" is the default password for the java keystore included in the container by default in this path "/layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts"

The only issue that I see is that I had a huge latency from my local machine to the Azure Redis and the logs were not showing in the correct order.

![image](https://github.com/user-attachments/assets/a593fd4d-88ee-464b-b42d-78e9e5a176fc)

So in theory the above should work to use SSL with REDIS.
