### ISSUE TITLE
Storage backend with AWS

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1422]
### Feedback

Hi ! 

I have an issue regarding the set up of the storage backend with AWS. The docs [https://docs.terrakube.io/getting-started/deployment/storage-backend/amazon-cloud-storage](state) that we should use access/secret keys to access the bucket. This force us to create static credentials which is not really a good practice. 

What we've done so far is that we made our kubernetes pod assume a role with kubernetes service account etc..
This role that will be used afterwards to perform the operations on our AWS account has the correct privilege. From my point of view I thought that from this section
```
storage:
  defaultStorage: false
  aws:
    accessKey: "rqerqw"
    secretKey: "sadfasfdq"
    bucketName: "qerqw"
    region: "us-east-1"
```

and transform it into
```
storage:
  defaultStorage: false
  aws:
    bucketName: "qerqw"
    region: "us-east-1"
```

Since the pod is already assuming a role and is therefore already authenticated through AWS we don't need to provide access and secret keys once again to put objects in that bucket.

When I tried to do as above I got the error
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'org.terrakube.storage.type' to org.terrakube.api.plugin.storage.configuration.StorageTypeEnum:

    Property: org.terrakube.storage.type
    Value: "${StorageType}"
    Origin: class path resource [application.properties] - 110:28
    Reason: failed to convert java.lang.String to org.terrakube.api.plugin.storage.configuration.StorageTypeEnum (caused by java.lang.IllegalArgumentException: No enum constant org.terrakube.api.plugin.storage.configuration.StorageTypeEnum.${StorageType})

Action:

Update your application's configuration. The following values are valid:

    AWS
    AZURE
    GCP
    LOCAL
```

I wonder if it is possible to make the access and secret optional so that we can use our home made role assuming to write backend into s3 ?

Thanks for reading !
Have a good day
