### ISSUE TITLE
Question regarding keycloak role with Terrakube

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1547]
### Feedback

Hi ! 

We currently have a set up to use Keycloak with groups for Terrakube everything works well ! 
However, as groups are not assigned to clients but are common to a realm it would be cleaner to use keycloak roles instead that are tied to a client.
I tried to trick the system by using the keycloak role into the groupKey value
```
dex:
  enabled: true
  podLabels:
    app: "terrakube-dex"
  config:
    issuer: xxx

    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']
      skipApprovalScreen: true
    oauth2:
      responseTypes: ["code", "token", "id_token"]

    connectors:
      - type: oidc
        id: keycloak
        name: keycloak
        config:
          issuer: xxx
          clientID: ${openid_user}
          clientSecret: ${client_secret}
          redirectURI: xxx
          scopes:
            - profile
            - email
            - roles
          insecureSkipEmailVerified: true
          insecureEnableGroups: true
          userIDKey: email
          userNameKey: email
          groupsKey: roles
```

Would you have any clue please ? :) I'm not sure if it is doable ?

Kind regards !
