### ISSUE TITLE
Drift detection customisation

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube#1548]
### Feedback

Hi ! 

We would like to customise the default drift_detection provided on the Terrakube [documentation](https://docs.terrakube.io/user-guide/drift-detection). In its current state the template exec a plan and returns a slack message depending on the changes. However, if the plan fails for some reason the drift template returns nothing and we have no information about that. I see that the plan is triggered by the lines
```
flow:
  - type: "terraformPlan"
    step: 100
    name: "Running Terraform Plan with Drift Detection and Slack Notification"
```

But I wonder if this is a kind of shortcut for Terrakube itself ? Also, if the plan if failing during those lines the rest of the code will never execute and we have no options catch the error. Do you know if there's a way to bypass that behavior ?

Regards ! 
Benjamin
