### ISSUE TITLE
AwsEnableRoleAuth (Amazon Cloud Storage) not working

### ISSUE THREAD

**Issue by andrew-zolotaryov-deel** [AzBuilder/terrakube#1749]
### Bug description 🐞

The `AwsEnableRoleAuth` environment variable is not working as expected, and the IRSA (IAM Roles for Service Accounts) configuration is not functioning correctly.

### Steps to reproduce

Terrakube helm values:
```    
  storage:
    defaultStorage: false
    aws:
      accessKey: "12345"
      secretKey: "12345"
      bucketName: "myBucket"
      region: "eu-west-1"

  api
    version: "2.24.0"
    serviceAccountName: terrakube
    env:
    - name: AwsEnableRoleAuth
      value: "true"
    - name: ExecutorEphemeralImage
      value: azbuilder/executor:2.24.0
 executor:
    version: "2.24.0"
    serviceAccountName: terrakube
    env:
    - name: AwsIncludeBackendKeys
      value: "false"
    - name: AwsEnableRoleAuth
      value: "true"

  registry:
    version: "2.24.0"
    env:
    - name: AwsEnableRoleAuth
      value: "true"
```

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terrakube
  namespace: terrakube
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::X:role/terrakube
```

Error that I'm receiving is:
```
***************************************
Running Terraform Init: 
Initializing the backend...
���
��� Error: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: X, api error InvalidClientTokenId: The security token included in the request is invalid.
��� 
��� 
���
***************************************
Running Terraform PLAN
***************************************
���
��� Error: Backend initialization required, please run "terraform init"
��� 
��� Reason: Initial configuration of the requested backend "s3"
��� 
��� The "backend" is the interface that Terraform uses to store state,
��� perform operations, etc. If this message is showing up, it means that the
��� Terraform configuration you're using is using a custom configuration for
��� the Terraform backend.
��� 
��� Changes to backend configurations require reinitialization. This allows
��� Terraform to set up the new configuration, copy existing state, etc. Please
��� run
��� "terraform init" with either the "-reconfigure" or "-migrate-state" flags
��� to
��� use the current configuration.
��� 
��� If the change reason above is incorrect, please verify your configuration
��� hasn't changed and try again. At this point, no changes to your existing
��� configuration or state have been made.
���



### Expected behavior

IRSA should work correctly with the `AwsEnableRoleAuth` environment variable set to `true`.
Executors should assume role from the ServiceAccount's annotation `eks.amazonaws.com/role-arn`.

### Example repository

_No response_

### Anything else?

I verified the IRSA configuration by specifying `serviceAccountName: terrakube` in a debug pod and assuming the role successfully.
Terrakube apply succeeded with a Access Key + Secret Key (IAM User with the same policies attached)

**Comment by alfespa17** [comment]
Hello @andrew-zolotaryov-deel, I think this is related to this discussion

https://github.com/orgs/AzBuilder/discussions/1728

**Comment by andrew-zolotaryov-deel** [comment]
Yes, I'm using the ephemeral executors, I configured the `EPHEMERAL_CONFIG_SERVICE_ACCOUNT: terrakube` parameter inside global variables, also verified that the k8s jobs are running with the `serviceAccountName: terrakube` specified.

Will appreciate any other advise.

<img width="1250" alt="Image" src="https://github.com/user-attachments/assets/d91ecbc0-b2f1-4650-9fa9-db1e466a5fdc" />

**Comment by andrew-zolotaryov-deel** [comment]
Attaching a Pod manifest as an example with all parameters:
```
apiVersion: v1
kind: Pod
metadata:
  name: job-38-hkglh
  namespace: terrakube
  labels:
    batch.kubernetes.io/job-name: job-38
    job-name: job-38
spec:
  containers:
    - name: job-38
      image: azbuilder/executor:2.24.0
      env:
        - name: EphemeralFlagBatch
          value: 'true'
        - name: EphemeralJobData
          value: '[REDACTED]'  # Redacted sensitive data
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        - name: AWS_DEFAULT_REGION
          value: eu-west-1
        - name: AWS_REGION
          value: eu-west-1
        - name: AWS_ROLE_ARN
          value: 'arn:aws:iam::X:role/terrakube'  # Redacted
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      volumeMounts:
        - name: kube-api-access-wsgwf
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        - name: aws-iam-token
          readOnly: true
          mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      imagePullPolicy: IfNotPresent
  restartPolicy: Never
  serviceAccountName: terrakube

**Comment by andrew-zolotaryov-deel** [comment]
I tried disabling ephemeral runners and to run the plan on `executor` pod, it received this error:
```
[threadPoolTaskExecutor-1] ERROR org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(org.terrakube.executor.service.mode.TerraformJob)
software.amazon.awssdk.services.s3.model.S3Exception: User: arn:aws:sts::X:assumed-role/internal-eks-node-group-X/i-X is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::myBucket/tfstate/X/terraformLibrary.tfPlan" because no identity-based policy allows the s3:PutObject action (Service: S3, Status Code: 403, Request ID: X, Extended Request ID: X)
```
Looks like it runs with the EKS node's IAM Role and doesn't assume the Role that is listed in the `ServiceAccount`'s annotation and `AWS_ROLE_ARN` pod's env var

This is the executor pod's manifest:
```
apiVersion: v1
kind: Pod
metadata:
  name: terrakube-executor-5cf856d89-s88dv
  namespace: terrakube
  labels:
    app: terrakube-executor
    pod-template-hash: 5cf856d89
spec:
  volumes:
    - name: aws-iam-token
      projected:
        sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token
        defaultMode: 420
    - name: kube-api-access-4fhgc
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: terrakube-executor
      image: azbuilder/executor:2.24.0
      ports:
        - containerPort: 8090
          protocol: TCP
      envFrom:
        - secretRef:
            name: terrakube-executor-secrets
      env:
        - name: AwsIncludeBackendKeys
          value: 'false'
        - name: AwsEnableRoleAuth
          value: 'true'
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        - name: AWS_DEFAULT_REGION
          value: eu-west-1
        - name: AWS_REGION
          value: eu-west-1
        - name: AWS_ROLE_ARN
          value: arn:aws:iam::X:role/terrakube
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      resources: {}
      volumeMounts:
        - name: kube-api-access-4fhgc
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        - name: aws-iam-token
          readOnly: true
          mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
  serviceAccountName: terrakube
  serviceAccount: terrakube
```

This is `backend.tf` file inside the Terraform code:
```
provider "aws" {
  region  = "eu-west-1"

  assume_role {
    role_arn = "arn:aws:iam::Y:role/terrakube"
  }
}

terraform {
  required_version = ">= 1.0.0, < 2.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.72"
    }
  }

  # for saving state on s3 bucket
  backend "s3" {
    bucket         = "myBucketName"
    key               = "terraform.tfstate"
    region         = "eu-west-1"
    dynamodb_table = "terraform-lock"
    role_arn       = "arn:aws:iam::X:role/terrakube"
  }
}
```
