### ISSUE TITLE
Empty environment variables being passed to executors

### ISSUE THREAD

**Issue by aniekgul** [AzBuilder/terrakube#1750]
### Bug description 🐞

Using chart version: 3.24.0 and with or without using ephemeral executors, we are seeing the value of the `GOOGLE_CREDENTIALS` be empty. The variable is set as a sensitive global variable. The database table `globalvar` has the correct value, all on a single line.

Easily noticeable when inspecting the created job when using ephemeral executors and checking the `EphemeralJobData` which looks like below:
```
...
"environmentVariables":{"GOOGLE_CREDENTIALS":"","EPHEMERAL_CONFIG_NODE_SELECTOR_TAGS":"node-role/terraform=true","EPHEMERAL_CONFIG_TOLERATIONS":"terraform:Exists:NoSchedule","TERRAKUBE_ENABLE_EPHEMERAL_EXECUTOR":"1","TF_IN_AUTOMATION":"1"
...
```

The same variable works in Terraform Cloud but leads to 403s here.

### Steps to reproduce

1. Set an environment variable `GOOGLE_CREDENTIALS` with the service account key on a single line
2. Run a job with the google provider

**Comment by alfespa17** [comment]
Maybe you can add this environment variable when you deploy terrakube using the helm chart to see the value that is sent:

```shell
JAVA_TOOL_OPTIONS="-Dlogging.level.org.terrakube.api.plugin.token.dynamic=DEBUG -Dlogging.level.org.terrakube.api.plugin.scheduler.job.tcl.executor=DEBUG"
```

And you can also modify the the template to show the value of the environment variable 


```yaml
flow:
  - type: "terraformPlan"
    step: 100
    commands:
      - runtime: "BASH"
        priority: 100
        before: true
        script: |
          echo $GOOGLE_CREDENTIALS
```

To validate the correct value is being used
