### ISSUE TITLE
Allow to use external Jwt to authenticate to the API

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#2055]
### Feature description 💡

Allow to use external token to authenticate to the terrakube API for example using the github token when using a pipeline or use a Azure service principal to authenticate to the API 

### Anything else?

Similar to dynamic credentials but using external service to authenticate to the API

**Comment by f0o** [comment]
would it be as simple as replacing the dexIssuerUri env var with the URL from a different OpenID provider? such as Authentik.

I'm looking into using terrakube but it feels odd to use two authentication providers (dex+authentik) just to relay our central IdP (Authentik).

So any pointers on being able to remove Dex and have terrakube use OpenID/OIDC directly would be great!

**Comment by alfespa17** [comment]
> would it be as simple as replacing the dexIssuerUri env var with the URL from a different OpenID provider? such as Authentik.
> 
> I'm looking into using terrakube but it feels odd to use two authentication providers (dex+authentik) just to relay our central IdP (Authentik).
> 
> So any pointers on being able to remove Dex and have terrakube use OpenID/OIDC directly would be great!

Not sure if replacing the dex url could work(I never tested that) 

You only need to add the dex oidc connector to use authentik similar to use Dex with cognito here 

https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/CognitoAuthentication-Example1.md#yaml-example

Dex config will be something like this inside your helm chart 

```yaml 
dex.config: |
    connectors:
    - config:
        issuer: https://authentik.company/application/o/<app>/
        clientID: <client ID from the Provider above>
        clientSecret: $dex.authentik.clientSecret
        insecureEnableGroups: true
        scopes:
          - openid
          - profile
          - email
      name: authentik
      type: oidc
      id: authentik
```
