### ISSUE TITLE
terraform login to terrakube api is not working

### ISSUE THREAD

**Issue by TigranKhudav** [AzBuilder/terrakube#2104]
### Bug description 🐞

terraform login to terrakube which is integrated with keycloak giving me page not found when redirecting to localhost:10000
my keycloak valid redirection url is `*`
i checked on my host listening 10000 port

### Steps to reproduce

this is my dex config 
```
    staticClients:
      - id: "keycloak"
        redirectURIs:
          - "https://terrakube.dev.my-domain"
          - "http://localhost:10001/login"
          - "http://localhost:10000/login"
          - "/device/callback"
        name: "keycloak"
        public: true
```

**Comment by BenjaminDecreusefond** [comment]
Hi @TigranKhudav

Can you try this
```
      staticClients:
        - id: terrakube
          redirectURIs:
            - 'https://terrakube.domain'
            - 'https://terrakube.domain/callback'
            - '/device/callback'
            - 'http://localhost:10000/login'
            - 'http://localhost:10001/login'
          name: terrakube
          public: true
```
