### ISSUE TITLE
Registry resources loading

### ISSUE THREAD

**Issue by TigranKhudav** [AzBuilder/terrakube#2143]
### Bug description 🐞

when I want to show module resources it is infinite loading...

![Image](https://github.com/user-attachments/assets/7b0fcc76-063d-4b46-b59e-e0071837d8f2)

### Steps to reproduce

when loading module resources there is no any logs about that in registry pode
and this is my registry configuration

```
## Registry properties
registry:
  enabled: true
  existingSecret: false
  image: azbuilder/open-registry
  version: "2.26.0-beta.7"
  replicaCount: "1"
  serviceType: "ClusterIP"
  serviceAccountName: ""
  secrets:
   - terrakube-registry-secrets
  otel:
    enabled: false
    metrics:
      port: "9464"
      host: "0.0.0.0"
    traces:
      type: jaeger
      # endpoint its just example, change it to your jaeger endpoint
      endpoint: "http://terrakube-api.minikube.net:9411/api/v2/spans" 
  env:
    - name: RegistryStorageType
      value: AwsStorageImpl
  resources: {}
  podAnnotations: {}
  podLabels: {}
  securityContext: {}
  containerSecurityContext: {}
  imagePullSecrets: []
  initContainers: []
```
