### ISSUE TITLE
CRDs to get values from manifest and convert it to terraform values

### ISSUE THREAD

**Issue by klinux** [AzBuilder/terrakube#2240]
### Feature description 💡

@alfespa17 @jcanizalez do you think that CRD to get values from manifest and convert it to terraform values, like crossplane do, can be a good idea? 

Example.

We have google SQL module, instead we write the file sql.tf with module values.
We have a manifest sql.yaml  with like this:

```
apiVersion: sql.gcp.terrakube.io/v1
kind: DatabaseInstance
metadata:
  name: teste
  labels:
    ...
  annotations:
    ...
spec:
  settings:
    region: "us-central"
    project: "project"
...
```

And we have something that do the drift detection like crossplane.

There another projects like burrito (https://github.com/padok-team/burrito) that think something like that too.

Do you think that makes sense?
