### ISSUE TITLE
Docker image task inside templates

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#296]
### Feature description 💡

Sometimes we need to execute scripts that require some external depedencies like for example powershell, nodejs, it could be a good idea to add support to run a docker image inside the templates .

```yaml
flow:
  - type: "customScripts"
    step: 100
    commands:
      - runtime: "dockerImage"
        priority: 200
        imageName: "powershell"
        imageVersion: "7.2.1"
        before: true
        script: |
          pwsh -v
```
