### ISSUE TITLE
Import template logic from git repository

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#313]
### Feature description 💡

Templates can become big over time, it could be a good idea to import "template logic from a GIT repository" to simplify the template structure,  like when using "Github Action" inside a pipeline.

Without Import logic:
```yaml
flow:
  - type: "terraformPlan"
    step: 100
    commands:
      - runtime: "import"
        priority: 100
        before: true
        script: |
          
          import TerraTag

          new TerraTag().downloadTerraTag("$workingDirectory", "0.1.29", "darwin", "amd64")
          "TerraTag Download Compledted..."
      - runtime: "BASH"
        priority: 200
        before: true
        script: |
          echo $PATH
          helloWorld.sh
          terratag.sh
  - type: "terraformApply"
    step: 300
```

Importing configuration
```yaml
flow:
  - type: "terraformPlan"
    step: 100
    importCommands:
      source: "https://github.com/AzBuilder/terrakube-extensions"
      folder: "Infracost"
      tag/branch: "main" 
      
  - type: "terraformApply"
    step: 300
```

Inside the GIT repository there should be a folder "infracost" with the following:

commands.yaml
```yaml
    commands:
      - runtime: "import"
        priority: 100
        before: true
        script: |
          
          import TerraTag

          new TerraTag().downloadTerraTag("$workingDirectory", "0.1.29", "darwin", "amd64")
          "TerraTag Download Compledted..."
      - runtime: "BASH"
        priority: 200
        before: true
        script: |
          echo $PATH
          helloWorld.sh
          terratag.sh
```

Internally Terrakube will have to create a "flattened template" before the job execution.

This will help to reuse logic in different templates.
