### ISSUE TITLE
Filter input variables

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#327]
### Feature description 💡

It could be a good idea to filter the global variables used during the imports base on the commands like the following:

```
flow:
  - type: "terraformPlan"
    step: 100
    inputs: 
            infracost_key: $INFRACOST_KEY
    importComands:
      repository: "https://github.com/AzBuilder/terrakube-extensions"
      folder: "templates/infracost"
      branch: "import-template"
      inputs: 
            infracost_key: $INFRACOST_KEY
  - type: "terraformApply"
    step: 200
```

In this way we can handle different global variables and send to the workspace in different situations
