### ISSUE TITLE
Context API fails in docker-compose

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#360]
### Bug description 🐞

There is a bug in the UI when using the context api inside docker-compose

The UI is trying to call the following URL.
http://terrakube-api/context/v1/1

The correct value should be:
http://terrakube-api:8080/context/v1/1

https://github.com/AzBuilder/terrakube/blob/main/ui/src/domain/Jobs/Details.jsx#L217

The env-config.js is the following:

```yaml
window._env_ = {
  REACT_APP_TERRAKUBE_API_URL: "http://terrakube-api:8080/api/v1/",
  REACT_APP_CLIENT_ID: "example-app",
  REACT_APP_AUTHORITY: "http://terrakube-dex:5556/dex",
  REACT_APP_REDIRECT_URI: "http://terrakube-ui:3000",
  REACT_APP_REGISTRY_URI: "http://terrakube-registry:8075",
  REACT_APP_SCOPE: "email openid profile offline_access groups",
}
```

it looks like the port is missing, this only affects the app when using docker-compose.

Regarsd

### Steps to reproduce

Run a job using docker compose and check the UI logs

### Expected behavior

The context api should not fail in docker-compose
