### ISSUE TITLE
"No Data" in Terraform Version dropdown

### ISSUE THREAD

**Issue by NiklasRosenstein** [AzBuilder/terrakube#377]
### Bug description 🐞

I've deployed Terrakube 2.12.0 using the Helm chart. I've not modified the `api.terraformReleasesUrl`, so it's pointing to `https://releases.hashicorp.com/terraform/index.json` as is the default in the Helm chart. I can't find any reference in the docs about additional steps that may be necessary to populate the available Terraform versions.

---

![image](https://user-images.githubusercontent.com/1318438/233864273-37aad19c-b874-487a-ab36-1e4a2d0133d7.png)

---

### Steps to reproduce

Deploy latest version of Terrakube with Helm (I used the version from [this PR](https://github.com/AzBuilder/terrakube-helm-chart/pull/64)):

```yaml
USER-SUPPLIED VALUES:
api:
  defaultDatabase: false
  loadSampleData: false
  properties:
    databaseHostname: postgres.default.svc.cluster.local
    databaseName: terrakube
    databasePassword: REDACTED
    databaseType: POSTGRESQL
    databaseUser: terrakube
dex:
  config:
    issuer: https://terrakube.example.org/dex
    oauth2:
      responseTypes:
      - code
      - token
      - id_token
      skipApprovalScreen: true
    staticClients:
    - id: terrakube
      name: Terrakube
      public: true
      redirectURIs:
      - https://terrakube.example.org
      - https://terrakube.example.org/
      - http://localhost:10000/login
    storage:
      type: memory
    web:
      allowedOrigins:
      - https://terrakube.example.org
      http: 0.0.0.0:5556
ingress:
  api:
    domain: terrakube.example.org
    path: /(api|pat|remote|\\.well-known)/(.*)
    tlsSecretName: terrakube-tls
  dex:
    domain: terrakube.example.org
  registry:
    domain: terrakube.example.org
    path: /registry/(.*)
    tlsSecretName: terrakube-tls
  ui:
    domain: terrakube.example.org
    tlsSecretName: terrakube-tls
  useTls: true
security:
  dexClientId: terrakube
  dexClientScope: email openid profile offline_access groups
  dexIssuerUri: terrakube.example.org/dex
  existingSecret: true
  internalSecret: REDACTED
  ldapConfigSecretName: terrakube-ldap
  patSecret: REDACTED
  useOpenLDAP: true
storage:
  defaultStorage: false
  minio:
    accessKey: REDACTED
    bucketName: terrakube
    endpoint: https://ams1.vultrobjects.com
    secretKey: REDACTED
```

### Expected behavior

I would see a list of all Terraform versions available per the Hashicorp Terraform releases endpoint in the dropdown.

**Comment by NiklasRosenstein** [comment]
When I do a `terraform init`, Terrakube automatically creates a corresponding workspace with the current Terraform version. But I still don't see a version in the drop down so I can't create a Workspace through the UI.

**Comment by alfespa17** [comment]
Hello @NiklasRosenstein 

Can you validate if your cluster has access to "https://releases.hashicorp.com/terraform/index.json"???

If your cluster does not have access to the URL for some network restriction or firewall, you can create some internal endpoint.


Reference:

**Comment by NiklasRosenstein** [comment]
Hello @alfespa17, the cluster does not have any outbound restrictions, so it can `curl "https://releases.hashicorp.com/terraform/index.json"` just fine (I just tested from an `ingress-nginx` pod; the `terrakube-api` pod doesn't come with cURL).

**Comment by alfespa17** [comment]
The API expose the following endpoint:

https://terrakube-api.yourdomain.com/terraform/index.json

Can you do a curl to that endpoint check the response and check the pod logs.

```bash
kubectl logs terrakube-api-XXXX -n your_namespace
```

By the way I think you can just leave your ingress like this, and it should work.

```yaml
ingress:
  api:
    domain: terrakube.example.org
    path: /(.*)
    tlsSecretName: terrakube-tls
```
