### ISSUE TITLE
terraform login doesn't work

### ISSUE THREAD

**Issue by DENISKI** [AzBuilder/terrakube#491]
### Bug description 🐞

I have the issue with terraform login after successful install of Terrakube in GKE.

### Steps to reproduce

Install Terrakube in GKE with the next helm configuration (sanitized sensitive data of my company):
```
security:
  useOpenLDAP: false
  adminGroup: "terrakube_admin"
  dexClientId: "eDirectory"
  dexClientScope: "email openid profile offline_access groups"

dex:
  enabled: true
  config:
    issuer: https://terrakube-api.example.com/dex
    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']
      skipApprovalScreen: true
    oauth2:
      responseTypes: ["code", "token", "id_token"]
    connectors:
    - type: ldap
      name: "eDirectory"
      id: ldap
      config:
        host: ldap.example.com:636
        insecureNoSSL: false
        insecureSkipVerify: true
        bindDN: username
        bindPW: password
        usernamePrompt: Email Address
        userSearch:
          baseDN: ou=users,ou=example,o=org
          filter: "(&(objectClass=posixAccount)(|(groupMembership=cn=admins,ou=groups,ou=example,o=org)(groupMembership=cn=terrakube-users,ou=groups,ou=example,o=org)))"
          username: mail
          idAttr: DN
          emailAttr: mail
          nameAttr: fullName
        groupSearch:
          baseDN: ou=groups,ou=example,o=org
          filter: "(objectClass=posixGroup)"
          userMatchers:
          - userAttr: DN
            groupAttr: member
          nameAttr: cn
    staticClients:
    - id: "eDirectory"
      redirectURIs:
      - 'https://terrakube-ui.example.com'
      - '/device/callback'
      - 'http://localhost:10000/login'
      - 'http://localhost:10001/login'
      name: 'eDirectory'
      public: true

## Terraform Storage
storage:
  defaultStorage: false
  gcp:
    projectId: "terrakube"
    bucketName: "terrakube"
    credentials: gce-json-sa-key

## API properties
api:
  enabled: true
  replicaCount: "1"
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
  serviceType: "ClusterIP"
  defaultDatabase: false
  loadSampleData: false
  terraformReleasesUrl: "https://releases.hashicorp.com/terraform/index.json"
  properties:
    databaseType: "POSTGRESQL"
    databaseHostname: "postgres.terrakube.svc"
    databaseName: "terrakube"
    databaseUser: "username"
    databasePassword: "password"

## Executor properties
executor:
  enabled: true
  replicaCount: "1"
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
  serviceType: "ClusterIP"
  properties:
    toolsRepository: "https://github.com/AzBuilder/terrakube-extensions"
    toolsBranch: "main"

## Registry properties
registry:
  enabled: true
  replicaCount: "1"
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
  serviceType: "ClusterIP"

## UI Properties
ui:
  enabled: true
  replicaCount: "1"
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
  serviceType: "ClusterIP"

## Ingress properties
ingress:
  useTls: true
  includeTlsHosts: true
  ui:
    enabled: true
    domain: "terrakube-ui.example.com"
    path: "/(.*)"
    pathType: "ImplementationSpecific"
    annotations:
      kubernetes.io/ingress.allow-http: "true"
      kubernetes.io/ingress.class: "gce-internal"
      kubernetes.io/ingress.regional-static-ip-name: "terrakube-ui-lb-intip1"
  api:
    enabled: true
    domain: "terrakube-api.example.com"
    path: "/(.*)"
    pathType: "ImplementationSpecific"
    annotations:
      kubernetes.io/ingress.allow-http: "true"
      kubernetes.io/ingress.class: "gce-internal"
      kubernetes.io/ingress.regional-static-ip-name: "terrakube-api-lb-intip1"
  registry:
    enabled: true
    domain: "terrakube-reg.example.com"
    path: "/(.*)"
    pathType: "ImplementationSpecific"
    annotations:
      kubernetes.io/ingress.allow-http: "true"
      kubernetes.io/ingress.class: "gce-internal"
      kubernetes.io/ingress.regional-static-ip-name: "terrakube-registry-lb-intip1"
  dex:
    enabled: true
    path: "/dex/(.*)"
    pathType: "ImplementationSpecific"
    annotations:
      kubernetes.io/ingress.allow-http: "true"
      kubernetes.io/ingress.class: "gce-internal"
      kubernetes.io/ingress.regional-static-ip-name: "terrakube-api-lb-intip1"

```
Run:
```
terraform login terrakube-api.example.com
Terraform will request an API token for terrakube-api.example.com using OAuth.

This will work only if you are able to use a web browser on this computer to
complete a login process. If not, you must obtain an API token by another
means and configure it in the CLI configuration manually.

If login is successful, Terraform will store the token in plain text in
the following file for use by subsequent commands:
    /root/.terraform.d/credentials.tfrc.json

Do you want to proceed?
  Only 'yes' will be accepted to confirm.

  Enter a value: yes

Open the following URL to access the login page for terrakube-api.example.com:
    https://terrakube-api.example.com/dex/auth?scope=openid+profile+email+offline_access+groups&client_id=eDirectory&code_challenge=ep_S4SxgWFaUa7H_31bXbNfbBMZ3NGwi99vMz9n2I4g&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A10000%2Flogin&response_type=code&state=1e8a5798-104d-eb01-59e3-e3a67b54f809

Terraform will now wait for the host to signal that login was successful.

```
The above link redirects to `https://localhost:10000/login?code=weutucowxymbrf434sun6iovt&state=1e8a5798-104d-eb01-59e3-e3a67b54f809` and I receive `(failed)net::ERR_CONNECTION_REFUSED`

### Expected behavior

Dex should authorize remote terraform login via the link provided in the console.
