### ISSUE TITLE
Default user is unauthorized

### ISSUE THREAD

**Issue by divad1196** [AzBuilder/terrakube#618]
### Bug description 🐞

I want to try terrakube. (The only explanation provide is using gitpod which I don't want to use).
I am unable to do any action using the default created user admin@exemple.com

### Steps to reproduce

1. I installed a K8S cluster using k3d
2. I used the official helm chart as it is, without modifying it
3. I accessed the default host http://terrakube-ui.minikube.net and logged in using admin@exemple.com + admin combination
4. I opened the "create an organisation" menu, put a name and clicked "Create organisation"
5. Got silently refused with 401

![image](https://github.com/AzBuilder/terrakube/assets/43037556/f5d32da7-0ec0-4b8f-b4f4-4c1a0e9ea4a8)

### Expected behavior

1. Use helm chart
2. Log using default user
3. Be able to do some operations from the UI.

### Anything else?

As mentionned, I would prefer a documentation that is not related to any particular tool.
The "Getting started" should only rely on embedded UI and raw query example (e.g. using curl).

**Comment by alfespa17** [comment]
There are several ways you could test it.

For example you could use minikube, you can check the documentation here.

https://docs.terrakube.io/getting-started/deployment/minikube

The best way to test it is using https so you can use the terraform remote state locally like this:

https://docs.terrakube.io/getting-started/deployment/minikube-+-https

https://github.com/orgs/AzBuilder/discussions/548

I never used k3d but if you are receiving 401 maybe the error is related to your ingress, probably it is not forwarding the authorization header to the API.

For example when using minikube we add some configuration in the ingress to forward the authorization header like this:


https://github.com/AzBuilder/terrakube-helm-chart/blob/main/charts/terrakube/values.yaml#L226
```
## Ingress properties
ingress:
  useTls: false
  includeTlsHosts: true
  ui:
    enabled: true
    domain: "terrakube-ui.minikube.net"
    path: "/"
    pathType: "Prefix"
    tlsSecretName: tls-secret-ui-terrakube
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
  api:
    enabled: true
    domain: "terrakube-api.minikube.net"
    path: "/"
    pathType: "Prefix"
    tlsSecretName: tls-secret-api-terrakube
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
  registry:
    enabled: true
    domain: "terrakube-reg.minikube.net"
    path: "/"
    pathType: "Prefix"
    tlsSecretName: tls-secret-reg-terrakube
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
  dex:
    enabled: true
    path: "/dex/"
    pathType: "Prefix"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
```

I hope this can help you
