### ISSUE TITLE
Terrakube Executor Agents for Jobs

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#635]
### Feature description 💡

Currently if you are using a remote job it is executed inside the "executor component" this component can scale horizontally and can process a lot of job concurrently, but it could be a good idea to add a way to execute jobs in different "agents" like for example if necesarry run the job in a "agent" just for  one or more organizations, like having different "executors" based on some predefine rules inside the templates

**Comment by dawidmalina** [comment]
This could be also security enhancement where jobs (workflow) are executed within independent dynamically created container and not interfere with other jobs (workflow). This pattern is quite popular ex jenkins with kubernetes agent.

**Comment by alfespa17** [comment]
> This could be also security enhancement where jobs (workflow) are executed within independent dynamically created container and not interfere with other jobs (workflow). This pattern is quite popular ex jenkins with kubernetes agent.

I tried to do it this way using a separate container a long time ago but I was facing some kubernetes issue when creating the container I guess it was some  service account access restriction and I never had the time to fix it, even the executor component still have the code to run in a kind batch mode executing just one job if i remember correctly

**Comment by dawidmalina** [comment]
If you still have that change somewhere i could try to test and help with kubernetes part if you want.

**Comment by alfespa17** [comment]
> If you still have that change somewhere i could try to test and help with kubernetes part if you want.

I will search the error information, I should have somewhere in my notes and update here once I found it.

**Comment by alfespa17** [comment]
Executor agents documentation can be found in the following link and more information in the above pull request:

https://docs.terrakube.io/getting-started/deployment/self-hosted-agents

I will create a new issue to manage "Ephemeral Agents" that could be created and deleted automatically when running a job as another option that having a different "agent pools"

**Comment by alfespa17** [comment]
> This could be also security enhancement where jobs (workflow) are executed within independent dynamically created container and not interfere with other jobs (workflow). This pattern is quite popular ex jenkins with kubernetes agent.

Sorry @dawidmalina it took me a while to add the feature with ephemeral agents, if you still want to test it you can check the following pull request:

https://github.com/AzBuilder/terrakube/pull/1044

You can also check the following documentation.

https://docs.terrakube.io/getting-started/deployment/ephemeral-agents

For now the ephemeral agents can be tested like this using the helm chart:

```yaml
api:
  image: "azbuilder/api-server"
  version: "2.22.0-beta.5"
  serviceAccountName: "terrakube-api-service-account"
  env:
  - name: ExecutorEphemeralNamespace
    value: terrakube
  - name: ExecutorEphemeralImage
    value: azbuilder/executor:2.22.0-beta.5
  - name: ExecutorEphemeralSecret
    value: terrakube-executor-secrets
```
