### ISSUE TITLE
`terrakube login` doesn't work when using GitHub with Dex

### ISSUE THREAD

**Issue by igorbrites** [AzBuilder/terrakube#642]
### Bug description 🐞

I've installed Terrakube on EKS using GitHub as the connector for Dex, and login on the browser works. Though `terrakube login` expects some Azure fields to be provided, which is not the case. How the login should work in these cases?

### Steps to reproduce

Install Terrakube using the following values:

```yaml
security:
  useOpenLDAP: false
  adminGroup: "<<REDACTED>>"
  patSecret: "<<REDACTED>>"
  internalSecret: "<<REDACTED>>"
  dexClientId: "terrakube"
  dexClientScope: "email openid profile offline_access groups"
  dexIssuerUri: <<REDACTED>>
  existingSecret: false
  ldapConfigSecretName: terrakube-openldap-secrets

## Dex
dex:
  enabled: true
  existingSecret: false
  config:
    issuer: <<REDACTED>>

    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']
      skipApprovalScreen: true
    oauth2:
      responseTypes: ["code", "token", "id_token"]

    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: <<REDACTED>>
        orgs:
        - name: <<REDACTED>>
          teams:
          - <<REDACTED>>
        loadAllGroups: true
        teamNameField: slug
        useLoginAsID: true

    staticClients:
    - id: terrakube
      redirectURIs:
      - '<<REDACTED>>'
      - '/device/callback'
      - 'http://localhost:10000/login'
      - 'http://localhost:10001/login'
      name: 'terrakube'
      public: true

## Terraform Storage
storage:
  defaultStorage: false
  aws:
    accessKey: "<<REDACTED>>"
    secretKey: "<<REDACTED>>"
    bucketName: "<<REDACTED>>"
    region: "us-east-1"
```
