### ISSUE TITLE
Only run terraform plan for changes in the working directory

### ISSUE THREAD

**Issue by cfsnate** [AzBuilder/terrakube#654]
### Feature description 💡

When using a monorepo and multiple workspaces, default behavior is to auto plan on every commit.

Would be nice to have an option to plan only on commits with changes that occur within the workspace working directory path.

**Comment by cfsnate** [comment]
To add on to this. I may be missing something but it appears the automatic action is to run the Plan + Apply template on commits.

Is it possible to modify this behavior to run a different template on VCS changes? Or is the best action to modify the stock Plan + Apply template to do what's wanted?

**Comment by alfespa17** [comment]
Hello @cfsnate 

The default behavior is that it will execute a "plan+apply template in the organization" if you do a push in the same branch that you used when creating the workspace.

You could change the template and for example add an approval part, you can go to the organization settings and change a little bit the template, it could be something like this:

```yaml
flow:
  - name: "Plan"
    type: "terraformPlan"
    step: 100
  - type: "approval"
    name: "Approve Plan"
    step: 150
    team: "<APPROVER GROUP BASED ON DEX CONFIG>"
  - name: "Apply"
    type: "terraformApply"
    step: 200
```

The webhooks support was added recently, for now you can only use the "plan+apply" template but you could do some customization like the above logic to add an approval or any other customization.

In the future we could add a feature to execute differente templates depending on webhooks events, like for example just running a plan for changes in some specific branches.
