### ISSUE TITLE
Problem to add a user to admin group

### ISSUE THREAD

**Issue by patsch9** [AzBuilder/terrakube#698]
Hello,

I have installed terrakube and created an oidc connector for keycloak. The login works without any problems, but I can't add myself to the admin group. 

I have made the following configuration:

```
dex:
  config:
    connectors:
    - type: oidc
      id: XXX
      name: XXX
      config:
        issuer: https://id-test.XXX.de/realms/XXX
        clientID: terrakube
        clientSecret: XXX
        redirectURI: https://terrakube-api.XXX.XXX/dex/callback
        basicAuthUnsupported: true
        scopes:
          - profile
          - email
        insecureSkipEmailVerified: true 
        insecureEnableGroups: true
        getUserInfo: true
        providerDiscoveryOverrides:




    issuer: https://terrakube-api.XXX.XXX/dex
    oauth2:
      responseTypes:
      - code
      - token
      - id_token
    staticClients:
    - id: XXX
      name: XXX
      public: true
      redirectURIs:
      - https://terrakube-ui.XXX.XXX
      - /device/callback
      - http://localhost:10000/login
      - http://localhost:10001/login
    storage:
security:
  adminGroup: "TERRAKUBE_ADMIN"
  dexClientId: XXX
  dexClientScope: email openid profile offline_access groups
  dexIssuerUri: https://XXX/dex
```

After logging in, I always get the "grant access" window, after which I continue to the start page, but then I can't do anything else. The following entry appears in the browser console: ajaxIntercept.js:47 - GET https://terrakube-api.XXX.XXX/api/v1/organization 401 (Unauthorised)

In the Network Trace there ist the following:
`Www-Authenticate:
Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"`
In the output of the Dex container I get the following: 

`time="2024-02-09T11:23:30Z" level=info msg="login successful: connector \"XXX\", username=\"Patrick Schmidt\", preferred_username=\"XXX@XXX.XXX\", email=\"XXX.XXX@XXX.XXX(unverified)\", groups=[\"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"XXX\" \"TERRAKUBE_ADMIN\"]"
`

> XXX is hidden for this issue

In the log of Dex the admin group is included, but I cannot perform any actions in the interface, there is always an HTTP 401.

We provide kubernetes with rancher and rke2.
We dont Use nginx as ingress controller in our cluster. 
We use the netscaler ingress controller. So the nginx annotations does not have any effect.

Anyone can help?

Thank's a lot

Patrick

**Comment by patsch9** [comment]
fresh installation with fresh secrets has helped

**Comment by alfespa17** [comment]
Hello @patsch9, I am glad that you were able to fix your issue, just one small comment about your configuration yaml, dont forget to change the default values for the token security

```yaml
security:
  patSecret: "AAAAAAAAAAAAAAAAAAAA"
  internalSecret: "BBBBBBBBBBBBBBBBB"
```

Reference: https://docs.terrakube.io/getting-started/deployment/token-security
