### ISSUE TITLE
Add custom commands inside a template

### ISSUE THREAD

**Issue by jcanizalez** [AzBuilder/terrakube#70]
There is a lot of community tools for Terraform right now and probably the best option to run custom tools in a flow is to create a Plugin #37  this could be required a certain amount of time to create a wrapper in  a plugin.

So an alternative option is allow to use custom commands inside a template. so once Templates are supporte #68, allow users to run terraform open source tools without the need to create a plugin or wrapper, this empower user to access already existing tools without the need to wait until a plugin is available.

Lets say we want to use terratag in our template https://github.com/env0/terratag but there is not an available plugin yet for that.

YAML
``` yaml
run:
   - terraform: init
   - commad: "terratag  --tags {\"environment_id\": \"prod\"} "
        url: "https://github.com/env0/terratag/releases/download/v0.1.29/terratag_0.1.29_linux_amd64.tar.gz"
        enforcement-level: mandatory
   - terraform: plan
   - terraform: apply

```

So in this case after the **command:** reserved word a url with a tar.gz file is optional, terrakube will download and unzip the file and then will be run the command, so terrakube will execute

`terratag -tags={\"environment_id\": \"prod\"}`

enforcement-level : advisory tasks can not block a run from completing. If the command fails, a warning will be displayed on the run but it will proceed.
mandatory commands can block a run from completing. If the command fails (including a timeout or unexpected error condition), a warning will be displayed on the run and the run will transition to an Errored state.
