### ISSUE TITLE
No Such File or Directory: Local Lambda Directory

### ISSUE THREAD

**Issue by gdacal** [AzBuilder/terrakube#852]
### Bug description 🐞

When executing a terraform apply command in a Terrakube setup, the expected directory home/cnb/.terraform-spring-boot/executor/<organization_id>/<workspace_id>/builds/lambda_function_<sha256>.zip is not created, which results in a failure with the error: Error: reading ZIP file (builds/lambda_function_<sha256>.zip): open builds/lambda_function_<sha256>.zip: no such file or directory.

### Steps to reproduce

1. **Requirements:**
   - Create an organization in Terrakube.
   - Create a workspace in the organization, either as CLI-driven or VCS, but ensure remote execution is enabled.

2. **Setup:**
   - Use the following module to set up a GitLab runner using version 7.5.0 from the provided module [cattle-ops/gitlab-runner/aws](https://registry.terraform.io/modules/cattle-ops/gitlab-runner/aws/latest).
   - Example invocation:
     ```hcl
     module "vpc" {
       source  = "terraform-aws-modules/vpc/aws"
       version = "5.8.1"

       name = "vpc-${var.environment}"
       cidr = "10.0.0.0/16"

       azs                     = [data.aws_availability_zones.available.names[0]]
       private_subnets         = ["10.0.1.0/24"]
       public_subnets          = ["10.0.101.0/24"]
       map_public_ip_on_launch = false

       enable_nat_gateway = true
       single_nat_gateway = true

       tags = {
         Environment = var.environment
       }
     }

     module "gitlab-runner" {
       source  = "cattle-ops/gitlab-runner/aws"
       version = "7.5.0"
       vpc_id    = module.vpc.vpc_id
       subnet_id = element(module.vpc.private_subnets, 0)
       environment = var.environment
       runner_gitlab = {
         url = var.gitlab_url
         registration_token = var.registration_token
       }
     }
     ```

3. **Run Terrakube in Docker Compose:**
   1. Access the executor container:
      ```sh
      docker exec -it <executor_container_id> bash
      ```
   2. Navigate to the path in executer container:
      ```sh
      cd /home/cnb/.terraform-spring-boot/executor/<organization_id>/<workspace_id>/
      ```
   3. Execute `terraform plan` on local directory invocation terraform code:
      ```sh
      terraform plan
      ```
      - Observe that Terraform files are created and the module repository is cloned within the `.terraform` directory on the executor container.
      - A directory `/home/cnb/.terraform-spring-boot/executor/<organization_id>/<workspace_id>/builds/lambda_function_<sha256>.zip` is created before the plan completes.
   4. After `terraform plan` completes, the files in `/home/cnb/.terraform-spring-boot/executor/<organization_id>/<workspace_id>/` are deleted.
   5. Run `terraform apply`:
      - The steps from 3 to 6 are repeated.
      - However, the directory `/home/cnb/.terraform-spring-boot/executor/<organization_id>/<workspace_id>/builds/lambda_function_<sha256>.zip` is not created again, leading to a failure.

### Expected behavior

The `terraform apply` should recreate the directory `/home/cnb/.terraform-spring-boot/executor/<organization_id>/<workspace_id>/builds/lambda_function_<sha256>.zip` as it did during the `terraform plan`, ensuring the process completes without errors.

**Error Message:**
```plaintext
Error: reading ZIP file (builds/lambda_function_<sha256>.zip): open builds/lambda_function_<sha256>.zip: no such file or directory

### Example repository

_No response_

### Anything else?

_No response_

**Comment by alfespa17** [comment]
Hello @gdacal 

I am not sure if I understand correctly using the module from `cattle-ops/gitlab-runner/aws` when running the terraform plan creates the directory `/builds/lambda_function_<sha256>.zip` that later is not available when running the "apply" because Terrakube clean the directory ?

**Comment by gdacal** [comment]
Hi @alfespa17,

Yes, this is the problem.
This module uses a lambda function that creates a local build .zip file.
After running terraform plan, this directory is cleaned, and during terraform apply, it fails because it can't find this file.

**Comment by alfespa17** [comment]
Currently you can save some information in your job execution but is limited as we explained [here](https://docs.terrakube.io/user-guide/organizations/templates/persistent-context) using this [extension](https://github.com/AzBuilder/terrakube-extensions/tree/main/groovy/Context) that can be used to save simple text file [here](https://github.com/AzBuilder/terrakube-extensions/blob/280a0d22cfb155659c21a45cc7f4e7d18bcfa2df/groovy/Context/Context.groovy#L21)

Maybe you could write some small script that encode the zip file in base64 so you can upload it using the context api so later you can download it when running the "apply" with a [custom template](https://docs.terrakube.io/user-guide/organizations/templates)

That will require some work but for now I think is the only alternative

**Comment by jcanizalez** [comment]
I think it's better if Terrakube uses the same folder for all the steps in the job and not a different folder for each step.

**Comment by alfespa17** [comment]
> I think it's better if Terrakube uses the same folder for all the steps in the job and not a different folder for each step.

The main issue is that the executor component is stateless and depending of your deployment you could have several[ agents pools](https://docs.terrakube.io/getting-started/deployment/self-hosted-agents) with many executor pods each one

**Comment by jcanizalez** [comment]
> > I think it's better if Terrakube uses the same folder for all the steps in the job and not a different folder for each step.
> 
> The main issue is that the executor component is stateless and depending of your deployment you could have several[ agents pools](https://docs.terrakube.io/getting-started/deployment/self-hosted-agents) with many executor pods each one

An option could be to write the files to a storage container (Azure, AWS, GCP, etc.) or to move the files to the container once the step is completed. Additionally, I think each step of the same job should be executed by the same executor. Otherwise, this adds more execution time for each job due to the wait time between each step, which can increase the total time. Is there any reason why each step is executed by different executor instances?

**Comment by gdacal** [comment]
Hi @alfespa17.


I tried what you told me but I still haven't been able to save the file after executing a plan.
I'll give you the template I'm using and the error
What could you be doing wrong?

Template:
```
flow:
- type: "terraformPlan"
  step: 100
  commands:
    - runtime: "BASH"
      priority: 100
      after: true
      script: |
        BASE64_ENCODED_ZIP=$(base64 "$workingDirectory/builds/lambda_function_9de860b79aae19cab2bd00759173d6ad23a6f563194f6e9b2acef79608a49066.zip")
        echo $BASE64_ENCODED > test_lambda.txt
    - runtime: "GROOVY"
      priority: 200
      after: true
      script: |
        import Context
        new Context("$terrakubeApi", "$terrakubeToken", "$jobId", "$workingDirectory").saveFile("lambda", "test_lambda.txt")
```
        
Error:
```
Begin Execution: 
Unable to determine the current character, it is not a string, number, array, or object

The current character read is [NEWLINE] with an int value of 10
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0

^
End Execution...
```

> Currently you can save some information in your job execution but is limited as we explained [here](https://docs.terrakube.io/user-guide/organizations/templates/persistent-context) using this [extension](https://github.com/AzBuilder/terrakube-extensions/tree/main/groovy/Context) that can be used to save simple text file [here](https://github.com/AzBuilder/terrakube-extensions/blob/280a0d22cfb155659c21a45cc7f4e7d18bcfa2df/groovy/Context/Context.groovy#L21)
> 
> Maybe you could write some small script that encode the zip file in base64 so you can upload it using the context api so later you can download it when running the "apply" with a [custom template](https://docs.terrakube.io/user-guide/organizations/templates)
> 
> That will require some work but for now I think is the only alternative

**Comment by alfespa17** [comment]
Can you try this @gdacal :

```
flow:
- type: "terraformPlan"
  step: 100
  commands:
    - runtime: "BASH"
      priority: 100
      after: true
      script: |
        base64 "$workingDirectory/builds/lambda_function_9de860b79aae19cab2bd00759173d6ad23a6f563194f6e9b2acef79608a49066.zip" > test_lambda.txt
    - runtime: "GROOVY"
      priority: 200
      after: true
      script: |
        import Context
        new Context("$terrakubeApi", "$terrakubeToken", "$jobId", "$workingDirectory").saveFile("lambda", "test_lambda.txt")
```

> By the way not sure if this text "9de860b79aae19cab2bd00759173d6ad23a6f563194f6e9b2acef79608a49066" in the zip file name is generated dynamically

**Comment by gdacal** [comment]
Hi @alfespa17 

Yes, when I manage to get it working I will stop dynamically.
But for the moment I will not have a problem because it generates the file with the same name if that lambda does not have changes.

I share the output with you, in the first step I do a cat to obtain the content of the file that contains the hash. But it fails to generate the context

```Command Priority 100
Running BASH
Script Information:  
sha256sum "$workingDirectory/builds/lambda_function_9de860b79aae19cab2bd00759173d6ad23a6f563194f6e9b2acef79608a49066.zip" | awk '{ print $1 }' > test_lambda.txt
cat test_lambda.txt




***************************************
Begin Execution: 
336604fb6feeed8f7729fd1422cbec8b155e18022921ee0028339f2a35f59630
End Execution... 



***************************************
Command Priority 200
Running GROOVY
Script Information:  
import Context
new Context("$terrakubeApi", "$terrakubeToken", "$jobId", "$workingDirectory").saveFile("lambda", "test_lambda.txt")



***************************************
Begin Execution: 
unexpected character f
End Execution... 
```

This is the template I use:

```
flow:
- type: "terraformPlan"
  step: 100
  commands:
    - runtime: "BASH"
      priority: 100
      after: true
      script: |
        sha256sum "$workingDirectory/builds/lambda_function_9de860b79aae19cab2bd00759173d6ad23a6f563194f6e9b2acef79608a49066.zip" | awk '{ print $1 }' > test_lambda.txt
        cat test_lambda.txt
    - runtime: "GROOVY"
      priority: 200
      after: true
      script: |
        import Context
        new Context("$terrakubeApi", "$terrakubeToken", "$jobId", "$workingDirectory").saveFile("lambda", "test_lambda.txt")
```

**Comment by alfespa17** [comment]
This should work for you @gdacal:

```yaml
flow:
  - type: "terraformPlan"
    step: 100
    name: "Plan"
    commands:
    - runtime: "BASH"
      priority: 100
      after: true
      script: |
        base64 "$workingDirectory/builds/lambda_function_9de860b79aae19cab2bd00759173d6ad23a6f563194f6e9b2acef79608a49066.zip" > base64File.txt
        sha256sum "$workingDirectory/builds/lambda_function_9de860b79aae19cab2bd00759173d6ad23a6f563194f6e9b2acef79608a49066.zip" | awk '{ print $1 }' > sha256sum.txt
        cat sha256sum.txt
    - runtime: "GROOVY"
      priority: 200
      after: true
      script: |
        import Context
       
        new Context("$terrakubeApi", "$terrakubeToken", "$jobId", "$workingDirectory").saveProperty("base64Data", new File("$workingDirectory" + "/base64File.txt").text)
  - type: "terraformApply"
    step: 200
    name: "Apply"
    commands:
    - runtime: "GROOVY"
      priority: 100
      before: true
      script: |
        import Context
        
        base64data = new Context("$terrakubeApi", "$terrakubeToken", "$jobId", "$workingDirectory").getContext("$jobId").base64Data
        
        println "File Data"
        println base64data

        new File("$workingDirectory" + "/base64FileV2.txt") << base64data
    - runtime: "BASH"
      priority: 200
      before: true
      script: |
        base64 --decode "$workingDirectory/base64FileV2.txt" > lambda_function_9de860b79aae19cab2bd00759173d6ad23a6f563194f6e9b2acef79608a49066.zip
        sha256sum "$workingDirectory/lambda_function_9de860b79aae19cab2bd00759173d6ad23a6f563194f6e9b2acef79608a49066.zip" | awk '{ print $1 }' > sha256sumV2.txt
        echo "New Zip File"
        cat sha256sumV2.txt
```

I did a small example using a zip file inside one of my workspaces and I got the same sha256sum as you can see here

![image](https://github.com/AzBuilder/terrakube/assets/4461895/bf81af8f-6e5d-4495-a0a9-b25dbb286bae)
