### ISSUE TITLE
Getting paketo-buildpacks error

### ISSUE THREAD

**Issue by MARVELMafia** [AzBuilder/terrakube#991]
### Feedback

I get the following error on my terrakube-api, executor, registory pods. 
![image](https://github.com/AzBuilder/terrakube/assets/28630442/d4ca4b0f-e3fa-4197-893c-cd9bcdba3203)

This is how I define the ca in the `values.yaml`

```
## API properties
    api:
      version: "2.19.2"
      env:
      - name: SERVICE_BINDING_ROOT
        value: /mnt/platform/bindings
      volumes:
        - name: ca-certs
          secret:
            secretName: terrakube-ca-secrets
            items:
            - key: "Fortinet.pem"
              path: "Fortinet.pem"
            - key: "type"
              path: "type"
      volumeMounts:
      - name: ca-certs
        mountPath: /mnt/platform/bindings/ca-certificates
        readOnly: true

    registry:
      version: "2.19.2"
      env:
      - name: SERVICE_BINDING_ROOT
        value: /mnt/platform/bindings
      volumes:
        - name: ca-certs
          secret:
            secretName: terrakube-ca-secrets
            items:
            - key: "Fortinet.pem"
              path: "Fortinet.pem"
            - key: "type"
              path: "type"
      volumeMounts:
      - name: ca-certs
        mountPath: /mnt/platform/bindings/ca-certificates
        readOnly: true

    executor:
      version: "2.19.2"
      env:
      - name: SERVICE_BINDING_ROOT
        value: /mnt/platform/bindings
      volumes:
        - name: ca-certs
          secret:
            secretName: terrakube-ca-secrets
            items:
            - key: "Fortinet.pem"
              path: "Fortinet.pem"
            - key: "type"
              path: "type"
      volumeMounts:
      - name: ca-certs
        mountPath: /mnt/platform/bindings/ca-certificates
        readOnly: true
```
The error I see is: 
```
failed to split certificates at path /mnt/platform/bindings/ca-certificates/Fortinet.pemfailed to decode PEM data
ERROR: failed to launch: exec.d: failed to execute exec.d file at path '/layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper': exit status 1
```

Any tips?
