### ISSUE TITLE
OpenTofu infracost support

### ISSUE THREAD

**Issue by syserr0r** [AzBuilder/terrakube#992]
Trying to use the infracost extension with an opentofu workspace results in the following output:

```
***************************************
Command Priority 200
Running BASH
Script Information:  
terraform show -json terraformLibrary.tfPlan > plan.json 
infracost breakdown --path plan.json



***************************************
Begin Execution: 
/home/cnb/.terraform-spring-boot/executor/85e6e129-2141-4e7d-b62d-14eb71af4b8d/9f326e6d-023e-461c-99f9-f9ee29c82e5b/userScript.sh: line 1: terraform: command not found
Error: Could not detect path type for plan.json

Use the --path flag to specify the path to one of the following:
 - Terraform plan JSON file
 - Terraform/Terragrunt directory
 - Terraform plan file
 - Terraform state JSON file

Update: A new version of Infracost is available: v0.9.11 ��� v0.10.37
  $ curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
Script Exit Code ==>1
End Execution... 
```

Changing the plan to read as follows:

```yaml
flow:
- type: "terraformPlan"
  step: 100
  commands:
    - runtime: "GROOVY"
      priority: 100
      after: true
      script: |
        import Infracost

        String credentials = "version: \"0.1\"\n" +
                "api_key: $INFRACOST_KEY \n" +
                "pricing_api_endpoint: https://pricing.api.infracost.io"

        new Infracost().loadTool(
           "$workingDirectory",
           "$bashToolsDirectory", 
           "0.10.37",
           credentials)
        "Infracost Download Completed..."
    - runtime: "BASH"
      priority: 200
      after: true
      script: |
        tofu show -json terraformLibrary.tfPlan > plan.json 
        infracost breakdown --path plan.json
```

Still does not yield working results (`tofu: command not found`) the output was:

```
***************************************
Command Priority 200
Running BASH
Script Information:  
tofu show -json terraformLibrary.tfPlan > plan.json 
infracost breakdown --path plan.json



***************************************
Begin Execution: 
/home/cnb/.terraform-spring-boot/executor/85e6e129-2141-4e7d-b62d-14eb71af4b8d/9f326e6d-023e-461c-99f9-f9ee29c82e5b/userScript.sh: line 1: tofu: command not found
Error: No valid Terraform files found at the given path, try a different directory

Try setting --path to a Terraform plan JSON file. See https://infracost.io/troubleshoot for how to generate this.

Update: A new version of Infracost is available: v0.10.12 ��� v0.10.37
  $ curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
Script Exit Code ==>1
End Execution... 
```

Any help would be greatly appreciated.
